#!/bin/bash

# Validate branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
if [[ ! $BRANCH_NAME =~ ^(main|ft/|tt/|rf/|cr/|wr/|fx/|hf/|dc/|ts|ch|auth|ds_system) ]]; then
  echo "Invalid branch name: $BRANCH_NAME"
  exit 1
fi

# Validate latest commit message
CONVENTIONAL_TYPES="feat|fix|docs|chore|refactor|perf|test|style|build|ci|revert|BREAKING CHANGE"
TICKET_TYPES="ft|tt|rf|cr|wr|fx|hf|dc|ts|ch"
COMMIT_MSG=$(git log --pretty=format:%s -1)
PATTERN="^(${CONVENTIONAL_TYPES}): \[(${TICKET_TYPES})\]\[GG-[0-9]{3}\]\ .+"
if [[ ! $COMMIT_MSG =~ $PATTERN ]]; then
  echo "Invalid commit message: $COMMIT_MSG"
  echo "Expected format: <type>: [tt][GG-018] Description"
  exit 1
fi

# Dart format check
changed_files=$(dart format --set-exit-if-changed .)
status=$?
if [ $status -ne 0 ]; then
  echo "Dart files need formatting. Please run 'dart format .' before pushing."
  echo "$changed_files"
  exit 1
fi

# Flutter analyze check
echo "Running flutter analyze before push..."
flutter analyze
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "Push rejected: flutter analyze failed."
  exit 1
fi
