name: golden_gate_app
packages:
  - packages/auth
  - packages/feature_commons

scripts:
  setup_hooks:
    description: "Configure git hooks before bootstrapping"
    run: |
      echo ":hook: Configuring Git Hooks... "
      chmod +x git_hooks/pre-push
      git config core.hooksPath git_hooks
      echo ":white_check_mark: Git hooks configured successfully."

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: false
    hooks:
      pre: melos run setup_hooks
      post: melos exec --order-dependents --concurrency=5 dart run build_runner build --delete-conflicting-outputs
  clean:
    hooks:
      post: melos exec --order-dependents --flutter --concurrency=1 -- "flutter clean"
