// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFshgzqeF9fYwcs2T0_7y86DXAV4XSut0',
    appId: '1:1024013348005:web:d24b4f1511027625c2314c',
    messagingSenderId: '1024013348005',
    projectId: 'goldengatemobileapp-7ac1a',
    authDomain: 'goldengatemobileapp-7ac1a.firebaseapp.com',
    storageBucket: 'goldengatemobileapp-7ac1a.firebasestorage.app',
    measurementId: 'G-8DLN6BELKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNUq3HgjX-RvGycAsxaF0QpQ_mbjQR55o',
    appId: '1:1024013348005:android:91a6b4f93a1616a1c2314c',
    messagingSenderId: '1024013348005',
    projectId: 'goldengatemobileapp-7ac1a',
    storageBucket: 'goldengatemobileapp-7ac1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdbC22NXcYydva_lAKkO8poAcF4NQBJaQ',
    appId: '1:1024013348005:ios:5df2587dabf6c1c3c2314c',
    messagingSenderId: '1024013348005',
    projectId: 'goldengatemobileapp-7ac1a',
    storageBucket: 'goldengatemobileapp-7ac1a.firebasestorage.app',
    iosBundleId: 'com.example.goldenGateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdbC22NXcYydva_lAKkO8poAcF4NQBJaQ',
    appId: '1:1024013348005:ios:5df2587dabf6c1c3c2314c',
    messagingSenderId: '1024013348005',
    projectId: 'goldengatemobileapp-7ac1a',
    storageBucket: 'goldengatemobileapp-7ac1a.firebasestorage.app',
    iosBundleId: 'com.example.goldenGateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFshgzqeF9fYwcs2T0_7y86DXAV4XSut0',
    appId: '1:1024013348005:web:5e6c2e23f92d1a53c2314c',
    messagingSenderId: '1024013348005',
    projectId: 'goldengatemobileapp-7ac1a',
    authDomain: 'goldengatemobileapp-7ac1a.firebaseapp.com',
    storageBucket: 'goldengatemobileapp-7ac1a.firebasestorage.app',
    measurementId: 'G-719Z92X9YW',
  );
}
