name: Convention Checks

on:
  pull_request:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          if [[ ! $BRANCH_NAME =~ ^(main|ft/|tt/|rf/|cr|wr|fx|hf|dc|ts|ch/) ]]; then
            echo "Invalid branch name: $BRANCH_NAME"
            exit 1
          fi
      - name: Validate commit messages
        run: |
          # Check all non-merge commit messages in the PR branch
          git log --pretty=format:%s --no-merges origin/${GITHUB_BASE_REF}..HEAD | while read COMMIT_MSG; do
            if [[ ! $COMMIT_MSG =~ ^(feat|fix|docs|chore|refactor|perf|test|style|build|ci|revert|BREAKING\ CHANGE):\ \[(ft|tt|rf|cr|wr|fx|hf|dc|ts|ch)\]\[GG-[0-9]{3}\]\ .+ ]]; then
              echo "Invalid commit message: $COMMIT_MSG"
              echo "Expected format: <type>: [tt][GG-018] Description"
              exit 1
            fi
          done
      - name: Install dependencies
        run: flutter pub get
      - name: Format check
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test
